/*
 * Copyright 2021 Stanisław Florczyk
 */
package view;

import controler.ControlerConfig;
import java.awt.event.WindowEvent;
import java.util.Dictionary;
import java.util.Hashtable;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.WindowConstants;

/**
 *
 * @author Stasio
 */
public class ViewConfig extends View
{
    private ControlerConfig controler;
    public DefaultListModel<String> usedTests = new DefaultListModel<>();
    public DefaultComboBoxModel<String> skippedTests = new DefaultComboBoxModel<>();
    /**
     * Creates new form ViewConfig
     */
    public ViewConfig(JTextArea ia,  ControlerConfig cc)
    {
        super("Ustawianie Parametrów Drzewa Decyzyjnego");
        infoArea = ia;
        controler = cc;
        initComponents();
        Dictionary  labelTable = new Hashtable();
        labelTable.put( new Integer(0), new JLabel("0%") );
        labelTable.put( new Integer(10), new JLabel("10%"));
        labelTable.put( new Integer(20), new JLabel("20%"));
        labelTable.put( new Integer(30), new JLabel("30%"));
        labelTable.put( new Integer(40), new JLabel("40%"));      
        labelTable.put( new Integer(50), new JLabel("50%")); 
        testSetSlider.setLabelTable(labelTable);
        if(controler.model.trainingSet != null)
        {
            for(String s : controler.model.trainingSet.headlines)
            {
                if(!controler.model.parameters.skippedTests.isEmpty())
                {
                    if(!controler.model.parameters.skippedTests.contains(s))
                    {
                        skippedTests.addElement(s);
                    }
                }else
                {
                    skippedTests.addElement(s);
                }
            }
            if(!controler.model.parameters.skippedTests.isEmpty())
            {
                for(String s : controler.model.parameters.skippedTests)
                {
                    usedTests.addElement(s);
                }
            }
        }
        
    }
    @Override
    public void createAndShow()
    {
        centerWindow(getSize().width, getSize().height);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        if(controler.model.trainingSet == null)
        {
            jLabel2.setEnabled(false);
            jLabel3.setEnabled(false);
            removeTestButton.setEnabled(false);
            restoreTestsButton.setEnabled(false);
            testsComboBox.setEnabled(false);
            skippedTestsList.setEnabled(false);  
            jLabel1.setEnabled(false);
            testSetSlider.setEnabled(false);
            testSetButton.setEnabled(false);
            setsSizeLabel.setEnabled(false);
            testToTrainButton.setEnabled(false);
        }else
        {
            jLabel2.setEnabled(true);
            jLabel3.setEnabled(true);
            removeTestButton.setEnabled(true);
            restoreTestsButton.setEnabled(true);
            testsComboBox.setEnabled(true);
            skippedTestsList.setEnabled(true);
            jLabel1.setEnabled(true);
            testSetSlider.setEnabled(true);
            testSetButton.setEnabled(true);
            setsSizeLabel.setEnabled(true);
            testToTrainButton.setEnabled(true);
        }
        controler.updateTestsSizeLabel(testSetSlider.getValue());
        setVisible(true);
    }
    @Override
    public void clearWorkSpace()
    {
        testSetSlider.setValue(100);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        testSetSlider = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        testsComboBox = new javax.swing.JComboBox();
        removeTestButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        restoreTestsButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        skippedTestsList = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        accuracySlider = new javax.swing.JSlider();
        testSetButton = new javax.swing.JButton();
        testToTrainButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        setsSizeLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Parametry Drzewa Decyzyjnego");
        setResizable(false);

        jLabel1.setText("Wielkość zbioru testowego:");

        testSetSlider.setMajorTickSpacing(10);
        testSetSlider.setMaximum(50);
        testSetSlider.setMinorTickSpacing(5);
        testSetSlider.setPaintLabels(true);
        testSetSlider.setSnapToTicks(true);
        testSetSlider.setToolTipText("");
        testSetSlider.setValue(10);
        testSetSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        testSetSlider.setInheritsPopupMenu(true);
        testSetSlider.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                testSetSliderStateChanged(evt);
            }
        });

        jLabel2.setText("Eliminacja konkretnych testów:");

        testsComboBox.setModel(skippedTests);

        removeTestButton.setText("Usuń");
        removeTestButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                removeTestButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Pomijane Testy:");

        restoreTestsButton.setText("Przywróć");
        restoreTestsButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                restoreTestsButtonActionPerformed(evt);
            }
        });

        skippedTestsList.setModel(usedTests);
        skippedTestsList.setToolTipText("");
        jScrollPane1.setViewportView(skippedTestsList);

        jLabel4.setText("Dokładność Drzewa - Przycinanie (%):");

        accuracySlider.setMajorTickSpacing(10);
        accuracySlider.setMinorTickSpacing(5);
        accuracySlider.setPaintLabels(true);
        accuracySlider.setPaintTicks(true);
        accuracySlider.setSnapToTicks(true);
        accuracySlider.setToolTipText("");
        accuracySlider.setValue(controler.model.parameters.accuracy);
        accuracySlider.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                accuracySliderStateChanged(evt);
            }
        });

        testSetButton.setText("Wydziel");
        testSetButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                testSetButtonActionPerformed(evt);
            }
        });

        testToTrainButton.setText("Wstaw Dane Zbioru Testowego do Zbioru Uczącego");
        testToTrainButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                testToTrainButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Zbiór Testowy");

        setsSizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setsSizeLabel.setText("0 / 0");

        saveButton.setText("Zapisz");
        saveButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(accuracySlider, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(testsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(removeTestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(restoreTestsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setsSizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(testSetSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(testSetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(testToTrainButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accuracySlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(testsComboBox)
                    .addComponent(removeTestButton, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(restoreTestsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(setsSizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(testSetSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(testSetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(testToTrainButton))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testSetSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_testSetSliderStateChanged
    {//GEN-HEADEREND:event_testSetSliderStateChanged
        controler.updateTestsSizeLabel(testSetSlider.getValue());
    }//GEN-LAST:event_testSetSliderStateChanged

    private void restoreTestsButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_restoreTestsButtonActionPerformed
    {//GEN-HEADEREND:event_restoreTestsButtonActionPerformed
        controler.restoreTests(skippedTestsList.getSelectedValuesList());
    }//GEN-LAST:event_restoreTestsButtonActionPerformed

    private void removeTestButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_removeTestButtonActionPerformed
    {//GEN-HEADEREND:event_removeTestButtonActionPerformed
        controler.skipTest((String)testsComboBox.getSelectedItem());
    }//GEN-LAST:event_removeTestButtonActionPerformed

    private void accuracySliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_accuracySliderStateChanged
    {//GEN-HEADEREND:event_accuracySliderStateChanged
        controler.setAccuracy(accuracySlider.getValue());
    }//GEN-LAST:event_accuracySliderStateChanged

    private void testSetButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testSetButtonActionPerformed
    {//GEN-HEADEREND:event_testSetButtonActionPerformed
        controler.createTestSet(testSetSlider.getValue());
    }//GEN-LAST:event_testSetButtonActionPerformed

    private void testToTrainButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testToTrainButtonActionPerformed
    {//GEN-HEADEREND:event_testToTrainButtonActionPerformed
        controler.restoreTrainingSet();
        setsSizeLabel.setText("0 / " + controler.model.trainingSet.table.get(0).size());
    }//GEN-LAST:event_testToTrainButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveButtonActionPerformed
    {//GEN-HEADEREND:event_saveButtonActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_saveButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider accuracySlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeTestButton;
    private javax.swing.JButton restoreTestsButton;
    private javax.swing.JButton saveButton;
    public javax.swing.JLabel setsSizeLabel;
    private javax.swing.JList skippedTestsList;
    private javax.swing.JButton testSetButton;
    private javax.swing.JSlider testSetSlider;
    private javax.swing.JButton testToTrainButton;
    private javax.swing.JComboBox testsComboBox;
    // End of variables declaration//GEN-END:variables
}
